# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='newuser',
        ),
        migrations.AddField(
            model_name='users',
            name='isnew',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
    ]
